matrix:
  include:
    - language: cpp
      os:
      - linux
      compiler:
        - g++
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc
          - g++
          - python3.7
      before_install:
        - sudo apt-get update
        - sudo apt-get install python3.7
        - gcc --version
      script:
        - python3 test.py
      after_success:
        - echo success!