matrix:
  include:
    - language: cpp
      os:
      - linux
      compiler:
        - g++
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc
          - g++
      before_install:
        - gcc --version
      script:
        - mkdir -p build
        - g++ src/library_test.cpp -o build/library_test.elf -std=c++11
        - ./build/library_test.elf
      after_success:
        - echo success!