matrix:
  include:
    - language: cpp
      os:
      - linux
      compiler:
        - gcc
      before_install:
        - echo $LANG
        - echo $LC_ALL
      after_success:
        - echo success!
      script:
        - mkdir -p build
        - g++ src/library_test.cpp -o build/library_test.elf -std=c++11
        - ./build/library_test.elf