matrix:
  include:
    - language: "c++"
      compiler:
        - gcc
      script:
        - mkdir -p build
        - g++ src/library_test.cpp -o build/library_test.elf -std=c++11
        - ./build/library_test.elf